name: ultimate_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0
  ultimate_shared:
    path: ../ultimate_shared
  web_socket_channel: ^3.0.3
  # path: ^1.9.0

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  lints: ^6.0.0
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  test: ^1.25.6
