name: _
publish_to: 'none'

environment:
  sdk: ^3.9.2

workspace:
  - packages/ultimate_shared
  - packages/ultimate_server
  - packages/ultimate_client

dependencies:
  auto_route: ^10.2.0
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  shelf: ^1.4.2
  shelf_web_socket: ^3.0.0

dev_dependencies:
  freezed: ^3.2.3
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  auto_route_generator: ^10.2.5