name: ultimate_client
description: "Ultimate Werewolf client."
publish_to: 'none'
version: 0.1.0

resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.2.0
  http: ^1.5.0
  google_fonts: ^6.3.2
  web_socket_channel: ^3.0.3
  uuid: ^4.5.1
  freezed_annotation: ^3.1.0
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  ultimate_shared:
    path: ../ultimate_shared
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  auto_route_generator: ^10.2.5
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
